### ISSUE TITLE
Uncaught ReferenceError: useState is not defined

### ISSUE THREAD

**Issue by Imadnajam** [Imadnajam/-React-Learning-Project-open-source-project-s-#12]
This error indicates that you're trying to use a React Hook (e.g., useState) without importing it from the 'react' library.

**Comment by bhavik001** [comment]
Hello @Imadnajam 
Can you explain the issue?

**Comment by Imadnajam** [comment]
hello @bhavik001  
the pobleme is 
 when you try to use a React Hook, such as useState, without importing it from the 'react' library.

**Comment by bhavik001** [comment]
Can you assign me the issue I am interested in working on it!

**Comment by Imadnajam** [comment]
@bhavik001 yes sure

**Comment by Imadnajam** [comment]
@Imadnajam  do anything you want like (add todo liste or CRUD) ... ,you can create a new file

**Comment by bhavik001** [comment]
Hello !
There are so many stuff which is commented and just got confused what to use?
